version: "3"

services:
    app:
        build: .
        env_file:
            - .env.prod
        volumes:
            - app_static:/app/static
    database:
        image: postgres:latest
        env_file:
            - .env.prod
        volumes:
            - database_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    webserver:
        image: nginx:latest
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - app_static:/var/www/static
        ports:
            - "8080:8081"
        depends_on:
            - app

volumes:
    app_static:
    database_data:
